# Generated by Django 5.1.2 on 2025-11-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('table_cible', models.CharField(max_length=50)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.apisource')),
            ],
        ),
        migrations.CreateModel(
            name='ApiFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_field', models.CharField(max_length=100)),
                ('internal_field', models.CharField(max_length=100)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='imports.apisource')),
            ],
            options={
                'unique_together': {('api', 'external_field')},
            },
        ),
    ]
